In [1]:
import mysql.connector, pandas as pd, datetime
flag_desserts=0
flag_breads=0
flag_cakes=0
flag_ms=0
flag_ff=0
flag_cookies=0
flag_pastries=0
flag_patties=0
newid=None
def login():
    x=1
    print("WELCOME TO JB CONFECTIONERY")
    uname=input("Enter username : ")
    passwd=input("Enter Password : ")
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        query="select * from login where id='%s' and password='%s';" % (uname,passwd)
        cursor.execute(query)
        result=cursor.fetchall()
        if len(result)>=1:
            while x!=5:
                print("Choose from the following")
                print("1. Desserts")
                print("2. Breads")
                print("3. Cakes")
                print("4. Milk Shakes")
                print("5. Fast Foods")
                print("6. Cookies")
                print("7. Pastries")
                print("8. Patties")
                print("9. Exit")
                x=int(input("Enter your choice :-  "))
                if x==1:
                    desserts()
                if x==2:
                    breads()
                if x==3:
                    cakes()
                if x==4:
                    milk_shakes()
                if x==5:
                    fast_foods()
                if x==6:
                    cookies()
                if x==7:
                    pastries()
                if x==8:
                    patties()
                if x==9:
                    break
            dataframe()
        else:
            print("Username doesn't exist")
    except Exception as e:
        print(e)
        
def dataframe():
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        global newid
        sql="select * from orders where id=%d" % (newid)
        cursor.execute(sql)
        results=cursor.fetchall()
        indx=[]
        cid=[]
        pn=[]
        price=[]
        qty=[]
        total=[]
        x=0
        for cols in results:
            cid.append(cols[0])
            pn.append(cols[1])
            price.append(cols[2])
            qty.append(cols[3])
            total.append(cols[5])
            x+=1
            indx.append(x)
        df=pd.DataFrame()
        df["Serial_No"]=indx
        df["Customer_ID"]=cid
        df["Product_Name"]=pn
        df["Price"]=price
        df["Quantity"]=qty
        df["Total"]=total
        df.set_index("Serial_No",inplace=True)
        print(df)
        db.commit()
        gtotal=sum(total)
        y=datetime.datetime.now()
        dt=y.strftime('%d-%m-%Y')
        print("Date of purchase : ",dt)
        print("YOUR GRAND TOTAL IS Rs.",gtotal)
        print("Thank you for shopping.")
    except Exception as e:
        print(e)
        
        
def signup():
    db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
    cursor=db.cursor()
    uname=input("Enter username : ")
    query="select * from login where id='%s'"%(uname)
    cursor.execute(query)
    results=cursor.fetchall()
    if len(results)>=1:
        print("Username already exists ")
    else:
        passwd=input("Enter Password : ")
        passwd2=input("Confirm Password : ")
        if passwd!=passwd2:
            print("PLEASE CHECK YOUR PASSWORD")
        else:
            try:
                db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
                cursor=db.cursor()
                query="insert into login values('%s','%s')"% (uname,passwd2)
                cursor.execute(query)
                db.commit()
                print("SIGN-UP SUCCESSFUL")
                login()
            except Exception as e:
                print(e)
                
def desserts():
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        query="select * from orders;"
        cursor.execute(query)
        results=cursor.fetchall()
        global newid
        for cols in results:
            newid=cols[0]
        global flag_desserts
        global flag_breads
        global flag_cakes
        global flag_ms
        global flag_ff
        global flag_cookies
        global flag_pastries
        global flag_patties
        if flag_desserts==0:
            newid=newid+1
            flag_desserts=1
            flag_breads=1
            flag_cakes=1
            flag_ms=1
            flag_ff=1
            flag_cookies=1
            flag_pastries=1
            flag_patties=1
        ch=input("Enter your choice from A. Gulab Jamun, B. Rasmalai, C. Laddoo : ")
        qty=int(input("Enter quantity required : "))
        y=datetime.datetime.now()
        dt=y.strftime('%Y-%m-%d')
        if ch=='A' or ch=='a':
            item="Gulab Jamun"
            price=20
        if ch=='B' or ch=='b':
            item="Rasmalai"
            price=25
        if ch=='C' or ch=='c':
            item="Laddoo"
            price=15
        tot=price*qty
        query="insert into orders values(%d,'%s',%d,%d,'%s',%d);" % (newid,item,price,qty,dt,tot)    
        cursor.execute(query)
        db.commit()
    except Exception as e:
        print(e)

def breads():
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        query="select * from orders;"
        cursor.execute(query)
        results=cursor.fetchall()
        global newid
        for cols in results:
            newid=cols[0]
        global flag_desserts
        global flag_breads
        global flag_cakes
        global flag_ms
        global flag_ff
        global flag_cookies
        global flag_pastries
        global flag_patties
        if flag_breads==0:
            newid=newid+1
            flag_desserts=1
            flag_breads=1
            flag_cakes=1
            flag_ms=1
            flag_ff=1
            flag_cookies=1
            flag_pastries=1
            flag_patties=1
        ch=input("Enter your choice from A. Whole Wheat, B. Multi Grain Bread, C. Burger Buns, D. Pizza Base :- ")
        qty=int(input("Enter quantity required : "))
        y=datetime.datetime.now()
        dt=y.strftime('%Y-%m-%d')
        if ch=='A' or ch=='a':
            item="Whole Wheat"
            price=35
        if ch=='B' or ch=='b':
            item="Multi Grain Bread"
            price=45
        if ch=='C' or ch=='c':
            item="Burger Buns(4 Pcs)"
            price=30
        if ch=='D' or ch=='d':
            item="Pizza Base"
            price=30
        tot=price*qty
        query="insert into orders values(%d,'%s',%d,%d,'%s',%d);" % (newid,item,price,qty,dt,tot)    
        cursor.execute(query)
        db.commit()
    except Exception as e:
        print(e)

def cakes():
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        query="select * from orders;"
        cursor.execute(query)
        results=cursor.fetchall()
        global newid
        for cols in results:
            newid=cols[0]
        global flag_desserts
        global flag_breads
        global flag_cakes
        global flag_ms
        global flag_ff
        global flag_cookies
        global flag_pastries
        global flag_patties
        if flag_cakes==0:
            newid=newid+1
            flag_desserts=1
            flag_breads=1
            flag_cakes=1
            flag_ms=1
            flag_ff=1
            flag_cookies=1
            flag_pastries=1
            flag_patties=1        
        ch=input("Enter your choice from A. Black Forest Cake, B. Pineapple Cake, C. Chocolate Cake, D. Oreo Cheese Cake : ")
        print("ALL THE CAKES ARE OF 1kg EACH AND WITH EGG")
        qty=int(input("Enter quantity required : "))
        y=datetime.datetime.now()
        dt=y.strftime('%Y-%m-%d')
        if ch=='A' or ch=='a':
            item="Black Forest Cake"
            price=350
        if ch=='B' or ch=='b':
            item="Pineapple Cake"
            price=325
        if ch=='C' or ch=='c':
            item="Chocolate Cake"
            price=375
        if ch=='D' or ch=='d':
            item="Oreo Cheese Cake"
            price=400
        tot=price*qty
        query="insert into orders values(%d,'%s',%d,%d,'%s',%d);" % (newid,item,price,qty,dt,tot)    
        cursor.execute(query)
        db.commit()
    except Exception as e:
        print(e)

def milk_shakes():
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        query="select * from orders;"
        cursor.execute(query)
        results=cursor.fetchall()
        global newid
        for cols in results:
            newid=cols[0]
        global flag_desserts
        global flag_breads
        global flag_cakes
        global flag_ms
        global flag_ff
        global flag_cookies
        global flag_pastries
        global flag_patties
        if flag_ms==0:
            newid=newid+1
            flag_desserts=1
            flag_breads=1
            flag_cakes=1
            flag_ms=1
            flag_ff=1
            flag_cookies=1
            flag_pastries=1
            flag_patties=1
        ch=input("Enter your choice from A. Rich Vanilla, B. Protein Coffee, C. Caramel, D. Oreo Chinno : ")
        qty=int(input("Enter quantity required : "))
        y=datetime.datetime.now()
        dt=y.strftime('%Y-%m-%d')
        if ch=='A' or ch=='a':
            item="Rich Vanilla"
            price=109
        if ch=='B' or ch=='b':
            item="Protein Coffee"
            price=125
        if ch=='C' or ch=='c':
            item="Caramel"
            price=139
        if ch=='D' or ch=='d':
            item="Oreo Chinno"
            price=150
        tot=price*qty
        query="insert into orders values(%d,'%s',%d,%d,'%s',%d);" % (newid,item,price,qty,dt,tot)    
        cursor.execute(query)
        db.commit()
    except Exception as e:
        print(e)

def fast_foods():
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        query="select * from orders;"
        cursor.execute(query)
        results=cursor.fetchall()
        global newid
        for cols in results:
            newid=cols[0]
        global flag_desserts
        global flag_breads
        global flag_cakes
        global flag_ms
        global flag_ff
        global flag_cookies
        global flag_pastries
        global flag_patties
        if flag_ff==0:
            newid=newid+1
            flag_desserts=1
            flag_breads=1
            flag_cakes=1
            flag_ms=1
            flag_ff=1
            flag_cookies=1
            flag_pastries=1
            flag_patties=1
        ch=input("Enter your choice from A. Grilled Sandwich, B. Burger, C. Veg Kathi Roll, D. Pizza : ")
        qty=int(input("Enter quantity required : "))
        y=datetime.datetime.now()
        dt=y.strftime('%Y-%m-%d')
        if ch=='A' or ch=='a':
            item="Grilled Sandwich"
            price=109
        if ch=='B' or ch=='b':
            item="Burger"
            price=125
        if ch=='C' or ch=='c':
            item="Veg Kathi Roll"
            price=139
        if ch=='D' or ch=='d':
            print("ALL PIZZAS ARE 6 inches REGULAR PAN PIZZAS")
            typ=int(input("Choose from (1.) Margherita (2.) Veggie Paradise (3.) Chicken Golden Delight (4.) Chicken Fiesta  :-  "))
            if typ=="1":
                item="Margherita"
                price=100
            if typ=="2":
                item="Veggie Paradise"
                price=195
            if typ=="3":
                item="Chicken Golden Delight"
                price=230
            if typ=="4":
                item="Chicken Fiesta"
                price=240
        tot=price*qty
        query="insert into orders values(%d,'%s',%d,%d,'%s',%d);" % (newid,item,price,qty,dt,tot)    
        cursor.execute(query)
        db.commit()
    except Exception as e:
        print(e)
        
def cookies():
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        query="select * from orders;"
        cursor.execute(query)
        results=cursor.fetchall()
        global newid
        for cols in results:
            newid=cols[0]
        global flag_desserts
        global flag_breads
        global flag_cakes
        global flag_ms
        global flag_ff
        global flag_cookies
        global flag_pastries
        global flag_patties
        if cookies==0:
            newid=newid+1
            flag_desserts=1
            flag_breads=1
            flag_cakes=1
            flag_ms=1
            flag_ff=1
            flag_cookies=1
            flag_pastries=1
            flag_patties=1
        ch=input("Enter your choice from A. Mixed Fruit Cookies, B. Crunchy Cookies, C. Oatmeal Cookies, D. Kesar Pista Badam Cookies :-  ")
        print("ALL THE PACKETS ARE OF 250 gms EACH")
        qty=int(input("Enter quantity required : "))
        y=datetime.datetime.now()
        dt=y.strftime('%Y-%m-%d')
        if ch=='A' or ch=='a':
            item="Mixed Fruit Cookies"
            price=80
        if ch=='B' or ch=='b':
            item="Crunchy Cookies"
            price=90
        if ch=='C' or ch=='c':
            item="Oatmeal Cookies"
            price=95
        if ch=='D' or ch=='d':
            item="Kesar Pista Badam Cookies"
            price=100
        tot=price*qty
        query="insert into orders values(%d,'%s',%d,%d,'%s',%d);" % (newid,item,price,qty,dt,tot)    
        cursor.execute(query)
        db.commit()
    except Exception as e:
        print(e)
        
def pastries():
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        query="select * from orders;"
        cursor.execute(query)
        results=cursor.fetchall()
        global newid
        for cols in results:
            newid=cols[0]
        global flag_desserts
        global flag_breads
        global flag_cakes
        global flag_ms
        global flag_ff
        global flag_cookies
        global flag_pastries
        global flag_patties
        if flag_pastries==0:
            newid=newid+1
            flag_desserts=1
            flag_breads=1
            flag_cakes=1
            flag_ms=1
            flag_ff=1
            flag_cookies=1
            flag_pastries=1
            flag_patties=1
        ch=input("Enter your choice from A. Black Forest Pastry, B. Pineapple Pastry, C. Cassata Pastry, D. Butterscotch Pastry : ")
        print("ALL THE PASTRIES ARE WITH EGG")
        qty=int(input("Enter quantity required : "))
        y=datetime.datetime.now()
        dt=y.strftime('%Y-%m-%d')
        if ch=='A' or ch=='a':
            item="Black Forest Pastry"
            price=40
        if ch=='B' or ch=='b':
            item="Pineapple Pastry"
            price=35
        if ch=='C' or ch=='c':
            item="Cassata Pastry"
            price=50
        if ch=='D' or ch=='d':
            item="Butterscotch Pastry"
            price=55
        tot=price*qty
        query="insert into orders values(%d,'%s',%d,%d,'%s',%d);" % (newid,item,price,qty,dt,tot)    
        cursor.execute(query)
        db.commit()
    except Exception as e:
        print(e)
        
def patties():
    try:
        db=mysql.connector.connect(user='root',password='tiger',host='127.0.0.1',database='sqltables')
        cursor=db.cursor()
        query="select * from orders;"
        cursor.execute(query)
        results=cursor.fetchall()
        global newid
        for cols in results:
            newid=cols[0]
        global flag_desserts
        global flag_breads
        global flag_cakes
        global flag_ms
        global flag_ff
        global flag_cookies
        global flag_pastries
        global flag_patties
        if flag_patties==0:
            newid=newid+1
            flag_desserts=1
            flag_breads=1
            flag_cakes=1
            flag_ms=1
            flag_ff=1
            flag_cookies=1
            flag_pastries=1
            flag_patties=1
        ch=input("Enter your choice from A. Aloo Mattar, B. Palak Paneer, C. Chilli Paneer, D. Aloo Shimla Mirch : ")
        qty=int(input("Enter quantity required : "))
        y=datetime.datetime.now()
        dt=y.strftime('%Y-%m-%d')
        if ch=='A' or ch=='a':
            item="Aloo Matar Patties"
            price=30
        if ch=='B' or ch=='b':
            item="Palak Paneer Patties"
            price=35
        if ch=='C' or ch=='c':
            item="Chilli Paneer Patties"
            price=40
        if ch=='D' or ch=='d':
            item="Aloo Shimla Mirch Patties"
            price=35
        tot=price*qty
        query="insert into orders values(%d,'%s',%d,%d,'%s',%d);" % (newid,item,price,qty,dt,tot)    
        cursor.execute(query)
        db.commit()
    except Exception as e:
        print(e)
        
print("(1.) SIGNUP (2.) LOGIN")
ask=int(input("Select your choice : "))
if ask==1:
    signup()
if ask==2:
    login()

ModuleNotFoundError: No module named 'mysql'